### ISSUE TITLE
[Feature] allow lowercased values

### ISSUE THREAD

**Issue by mimmi20** [prolic/fpp#10]
The example

```php
namespace MyEnum;

data BrowserType = application | bot | browser | pim deriving (Enum);
```

is actually generating an error.

```shell
Parse Error: Syntax error, definiton name application must be upper case at line 4 on file
```

Please allow lowercased values.

**Comment by prolic** [comment]
:+1: ok, maybe I have time this weekend to do that. But feel free to submit a PR. The needed change is in the parse function.

**Comment by prolic** [comment]
lower case is now allowed.
