### ISSUE TITLE
Add existing interfaces

### ISSUE THREAD

**Issue by hoffigk** [prolic/fpp#112]
Hi.

This is mainly a question. I need to implement an existing interface on an generated class.

Foo.fpp looks like this:
```
data Foo = Foo { string $a, string $b } deriving (Command);
```

The generated code is:
```
final class Foo extends \Prooph\Common\Messaging\Command {
...
```
What i need:

```
final class Foo extends \Prooph\Common\Messaging\Command implements \Prooph\ServiceBus\Async\AsyncMessage {
```

In my case i need to send the FooCommand async with the prooph service bus. If i understood it correctly, i have to enable the async_switch and implementing the interface `\Prooph\ServiceBus\Async\AsyncMessage`

How can i add existing interfaces?

**Comment by prolic** [comment]
Reusing interfaces or classes in FPP that are not generated by PHP but are defined somewhere in your code or in PHP core is currently not supported.

I'll get to that when I have some time.
