### ISSUE TITLE
Referring to classes that otherwise exist but not generated does not appear to work

### ISSUE THREAD

**Issue by simensen** [prolic/fpp#115]
I had a file that looked like this:

```
namespace App\Model\Subscription {
    data SubscriptionId = SubscriptionId deriving (Uuid);
}

namespace App\Model\Subscription\Event {
    data SubscriptionCreated = SubscriptionCreated {
        \App\Model\Subscription\SubscriptionId $subscriptionId,
        \App\Model\Account\AccountId $accountId
    } deriving (AggregateChanged);

    data SubscriptionCanceled = SubscriptionCanceled {
        \App\Model\Subscription\SubscriptionId $subscriptionId,
        \App\Model\Account\AccountId $accountId
    } deriving (AggregateChanged);
}
```

However, this gave me an error because `\App\Model\Account\AccountId` was not defined, even though that class actually exists on disk. While I suppose this makes sense to a certain degree, it was definitely not expected. Did I do something wrong or is this what should be happening?

**Comment by simensen** [comment]
I guess said another way, for classes/types specified in a specific `.fpp`, can you only reference other classes/types defined in that exact same `.fpp` file?

**Comment by simensen** [comment]
The use case would be something like this, where PostTodo from the Todo model references UserId from the User model:

https://github.com/prooph/proophessor-do-symfony/blob/master/src/ProophessorDo/Model/Todo/Command/PostTodo.php

The main problem (I think?) is I tried to separate my `.fpp` files by model to make them a little easier to manage:

```
config
└── model
    ├── account.fpp
    ├── form.fpp
    ├── subscription.fpp
    └── user.fpp
```

However, `Form` and `Subscription` are both going to refer to `AccountId` in some places. I was able to get it to work if I `cat *.fpp > model.fpp` but that is a bit less than ideal given how large that file is already getting. Especially since the verbosity of needing to specify the FQCN make things a little harder to scan.

I think the problem is potentially with the PHPStorm watcher. It apparently regenerates just the file that changes. However, if I run `fpp config/model` (and not specific files) things work better. I'm going to update my PHPStorm configuration to see if that works better from the IDE.

However, I suspect there might be cases where I'll want to create a custom value object I'll want to maintain by hand. In those cases, it seems like I won't be able to reference them from any of my other value objects.

Is there a way to reference a type that exists *without* having that type then be generated automatically?

**Comment by prolic** [comment]
You can give fpp a directory to scan for *.fpp files. It doesn't make a difference in which file your definition is, you can reference a class existing in one file within another one, but during the generation process all files must be present (hence the use of directory as argument).

As of now, you cannot reuse PHP's classes (like DateTimeImmutable) or your own custom ones. This may change in the future. It's not that easy to come up with a generic solution on how to generate to / from - array / string for objects unknown to fpp.
