### ISSUE TITLE
What is the best way to handle value objects that need customization? (additional methods, etc)

### ISSUE THREAD

**Issue by simensen** [prolic/fpp#117]
I often run into cases where value objects have additional behavior than just providing access to the data they store. They may also have several ways of being created (#41). Is there a way to handle value objects that need customization beyond just generating them once and then removing them from `.fpp` so the customization won't be clobbered?

**Comment by prolic** [comment]
Currently it's not possible, maybe at some point in the future. If you want to work on that, feel free to add this feature. But if so, let me know upfront, so we can discuss some details before you get started.
