### ISSUE TITLE
ToArray/FromArray do not support associative arrays

### ISSUE THREAD

**Issue by Adirelle** [prolic/fpp#120]
Due to the way fromArray and toArray operates on member arrays, the keys are lost on conversion. This is an issue with associative arrays when keeping the keys is desirable.

I think about two possible sultions:

1. quick and simple: simply keep the keys when converting arrays. No changes to declaration are needed but this can be seen as a breaking change since it alters the behavior of existing classes.
2. adds a way to declare "maps" without changing the way lists are declared. The question being: which syntax should be used? Two examples, with a value of type A:

| List of A | Int-indexed associative array of A | String-indexed associative array of A | Comment |
| --- | --- | --- | --- |
| `A[]` | `A[int]` | `A[string]` | Consistent, but unusual |
| `A[]` or `array<A>` | `array<int, A>` | `array<string, A>` | Supported by phpdocumentor/type-resolver >= 0.5 |

Any thought about this ?

**Comment by prolic** [comment]
@Adirelle I saw your PR's. Will take a look this week, super busy right now.
