### ISSUE TITLE
Wrong ternary operator in buildToArrayBody

### ISSUE THREAD

**Issue by markusmichel** [prolic/fpp#126]
I'd like to repoen #109 because the problem is still present.

These are the problematic lines of code:
https://github.com/prolic/fpp/blob/13063a0c135953ed641eb93d030eb6643ab22478/src/builder/buildToArrayBody.php#L152-L173

The ternary operator will be appended once for each deriving until the deriving equals one of `Enum`, `ToString`, `Uuid` etc.

Example:
```
data UserName = String deriving (Equals, FromString, ToString);
data User = User { ?UserName $userName } deriving (FromArray, ToArray);
```

```php
'userName' => null === $this->userName ? null : null === $this->userName ? null : null === $this->userName ? null : $this->userName->toString(),
```

Order matters: Correct output when `ToString` is the first argument

```
data UserName = String deriving (ToString, Equals, FromString);
```

```php
'userName' => null === $this->userName ? null : $this->userName->toString(),
```

Failing test:
https://github.com/markusmichel/fpp/commit/8fd79035fe3753da4067bead7c08d585f0686ec0

Solution:
Make sure that the null check + ternary operator will only be added once for each `Definition`.

**Comment by prolic** [comment]
Thanks, will look into it.

**Comment by prolic** [comment]
A release 0.1.0 has been tagged. There is currently a rewrite going on, so I will close all open issues. If you still want to resolve this issue yourself, you can submit a pull request to the 0.1.x branch.
