### ISSUE TITLE
Comment support in fpp files // and /* */

### ISSUE THREAD

**Issue by paales** [prolic/fpp#13]
I notices the need to provide comments in my fpp files, support would be nice :)

**Comment by prolic** [comment]
Thanks @paales for all your bug reports, I solved all critical ones as for now, but will leave this open as another task. It has not super high priority right now, but I think it's a nice addition.

**Comment by paales** [comment]
Thanks a lot! Created our first go at the domain model: 200 lines of FPP, 3k lines of PHP code, all valid :)

**Comment by prolic** [comment]
Comments are now allowed, thanks for your help.

**Comment by paales** [comment]
Awesome! We probably need to update the wiki for the PHPStorm file format so that comments are recognized.

**Comment by prolic** [comment]
Thanks for the hint about PhpSTorm integration, I updated the wiki.
