### ISSUE TITLE
"Cannot use 'ClassName' because the name is already in use"

### ISSUE THREAD

**Issue by Maikel-Koek** [prolic/fpp#19]
When inserting the same classes multiple times, the following problem occurs:

![schermafbeelding 2018-03-09 om 15 58 16](https://user-images.githubusercontent.com/6301809/37213562-b492a21a-23b2-11e8-9ab2-71a1aaff76a7.png)

**Comment by prolic** [comment]
Thanks for the report. I think I have to remove the imports again and use
absolute class names. Also reduces other collisions.

**Comment by prolic** [comment]
Thanks lot !!!
