### ISSUE TITLE
Delete classes when they aren't in the fpp file any more.

### ISSUE THREAD

**Issue by paales** [prolic/fpp#26]

**Comment by prolic** [comment]
I'm not sure about this one. We could add a flag and make it optional (like: `fpp.php src --delete`). But then we need to store the information of last parsing run somewhere. Maybe a `.fpp-generated-files` file can be put at the root of the repository. Not sure at the moment. I will leave it open for now.

**Comment by paales** [comment]
Maybe scan some files and see if they have a 'generated by fpp' string in it. Or have a separate --clean method or something.

**Comment by codeliner** [comment]
hard to solve but :+1:

A file called `fpp.lock` in project root sounds not that bad ;)
People are used to such files.

**Comment by prolic** [comment]
A release 0.1.0 has been tagged. There is currently a rewrite going on, so I will close all open issues. If you still want to resolve this issue yourself, you can submit a pull request to the 0.1.x branch.
