### ISSUE TITLE
PHP Storm integration path

### ISSUE THREAD

**Issue by paales** [prolic/fpp#33]
The filewatcher command path can be shortened to:
`$ProjectFileDir$/vendor/prolic/fpp/bin/fpp.php $FilePath$`

**Comment by prolic** [comment]
see https://github.com/prolic/fpp/wiki/PhpStorm-Integration

is that good now?

**Comment by prolic** [comment]
ping @paales

**Comment by paales** [comment]
That seems right :) We might be able to move all the wiki stuff to a docs folder, would be easier for me to suggest things. I can help with that some time if you'd like.

**Comment by prolic** [comment]
Sure sounds good. I'll disable the wiki page when finished and link to docs
folder instead.

Hint: you can clone the wiki as starting point
