### ISSUE TITLE
DateTime + DateInterval type

### ISSUE THREAD

**Issue by paales** [prolic/fpp#34]
Might be handy to have DateTime and DateInterval types.

**Comment by prolic** [comment]
Indeed, didn't had the time to work on it, yet.

**Comment by prolic** [comment]
Working on it now... see also https://github.com/prolic/fpp/issues/41

**Comment by prolic** [comment]
A release 0.1.0 has been tagged. There is currently a rewrite going on, so I will close all open issues. If you still want to resolve this issue yourself, you can submit a pull request to the 0.1.x branch.
