### ISSUE TITLE
ToArray can not be implemented for single array argument

### ISSUE THREAD

**Issue by paales** [prolic/fpp#35]
I am trying to do the following:

```fpp
data Projects = Projects { ProjectKey[] $projects } deriving (ToArray, ToString);
```

This isn't allowed, because it requires two arugments. ToString, FromString builds but that tries to do a toString() on an array but that doesn't work.

**Comment by paales** [comment]
I was trying to do the following but that didn't work, so I tried to create an argument first:

```
data GetProjects = GetProjects {
    ProjectKey[] $projects
} deriving(Query)
```

It also doesn't allow the following (requires at least one argument, but does a query need to have an argument?)

```
data GetProjects = GetProjects deriving(Query)
```

**Comment by prolic** [comment]
Thanks for the bug-report. I'll try to work on it asap.

**Comment by paales** [comment]
```
    data Change = Change {
        Uuid $uuid,
        Id $id,
        Author $author,
        Item[] $items //@todo array with deriving isn't supported yet.
    } deriving (FromArray, ToArray, Equals);
```

**Comment by prolic** [comment]
Please note:
`data Projects = Projects { ProjectKey[] $projects } deriving (ToArray, ToString);` - Deriving ToArray & ToString at the same time will not go well in most situations. Especially when the `$projects` is an array of `ProjectKey` - meaning it can never return a string representation successfully.

**Comment by prolic** [comment]
I am working on a fix for this problem, need to do some refactoring in order to make it work.

**Comment by paales** [comment]
>  Please note:
data Projects = Projects { ProjectKey[] $projects } deriving (ToArray, ToString); - Deriving ToArray & ToString at the same time will not go well in most situations. Especially when the $projects is an array of ProjectKey - meaning it can never return a string representation successfully.

Oh, that is an error in my example, wasn't in my domain model, thanks for pointing it out.

**Comment by paales** [comment]
Comments placed in the PR
