### ISSUE TITLE
data GetProjects = GetProjects deriving(Query) isn't allowed

### ISSUE THREAD

**Issue by paales** [prolic/fpp#40]
The Query deriving shouldn't require an argument, or should it?

**Comment by prolic** [comment]
That's right, should work without argument. Does it expect one?

**Comment by paales** [comment]
`PHP Fatal error:  Uncaught Fpp\InvalidDeriving: Invalid deriving on GetProjects, deriving Query expects at least one constructor argument in /Users/paulhachmang/Sites/soft3/src/vendor/prolic/fpp/src/InvalidDeriving.php:76
Stack trace:`
