### ISSUE TITLE
Define named constructors for non-derived entities

### ISSUE THREAD

**Issue by Sevavietl** [prolic/fpp#41]
While trying to use this great library, I find out that it is really problematic to use custom entities in the payload, because there is no mechanism to deduce the proper named constructor. 

For example, I use [marc-mabe/php-enum](https://github.com/marc-mabe/php-enum) for enums. It has `byValue($value)`, that can be used for constructing from inside `AggregateChanged` or `Command`.  I think it would be usefull to have some kind of config where I can define the list of named constructors like following:

```php
return [
    'Mabe\Enum' => 'byValue'
]
```

Then in the `buildArgumentConstructor` helper function we can use this mapping to build a construction. The code can look like the following:

```php
foreach ($mapping as $type => $method) {
    if (is_($argument->type(), $type, true)) {
        return "{$calledClass}::{$method}(\${$argument->name()})";
    }
}
```

If you like this approach I can provide a PR.

Thank you in advance.

**Comment by prolic** [comment]
This would need multiple places, like maybe you need to add
toString/fromString/toArray/fromArray capabilities. It's not that an easy
task. For some objects you may be able to configure some methods to use for
that, for others you may need additional params or even reflection. So if
you only have a particular use case (like mabe-enum), it may be easier to
configure another enun template and override the existing one, so all enuns
will generate mabe enums directly for you.

**Comment by prolic** [comment]
True. I didn't have the time to work on something like this yet. That said,
if you have time to contribute, it would be more then welcomed.

**Comment by Sevavietl** [comment]
I will try to come up with something.

**Comment by prolic** [comment]
Working on it now...

**Comment by prolic** [comment]
A release 0.1.0 has been tagged. There is currently a rewrite going on, so I will close all open issues. If you still want to resolve this issue yourself, you can submit a pull request to the 0.1.x branch.
