### ISSUE TITLE
fromString doesn't actually instantiate the field type

### ISSUE THREAD

**Issue by paales** [prolic/fpp#46]
```fpp
namespace A {
    data Uuid = Uuid deriving(Uuid);
}

namespace B {
    data Author = Author { \A\Uuid $author } deriving(FromString, ToString, Equals); 
}
```

I expect something like this:

```php
public static function fromString(string $author): Author
{
    return new self(\A\Uuid::fromString($author));
}
```

It actually generates:

```php
public static function fromString(string $author): Author
{
    return new Author($author);
}
```

**Comment by prolic** [comment]
Actually this doesn't work at the moment. I leave this ticket open as new feature request. As for now, you can only generate fromString for objects that represent string, not for objects that represent objects that represent string. Use toArray instead.

**Comment by paales** [comment]
Ahh, well if toArray and fromArray work, thats fine for now.
