### ISSUE TITLE
Suggestion: Use Assert library as an alternative to data validation.

### ISSUE THREAD

**Issue by felipeweb11** [prolic/fpp#5]
[webmozart/assert](https://github.com/webmozart/assert) is a powerful library that could help in validation.   
In this library, by default all assertions throw an InvalidArgumentException.

**Comment by prolic** [comment]
@felipeweb11 Thanks for the suggestion. I will probably remove the assert lib, because all code is generated either way, so I can generate the checks as well. No need for an additional library. I leave this open until it's addressed.

**Comment by prolic** [comment]
resolved via https://github.com/prolic/fpp/pull/8
