### ISSUE TITLE
Add MinLength(x) deriving

### ISSUE THREAD

**Issue by prolic** [prolic/fpp#50]
Note: This deriving requires an argument

/cc @codeliner

**Comment by gquemener** [comment]
The list of available deriving constraints could be inspired from the constraints provided in the [Symfony validator package](https://github.com/symfony/validator/tree/master/Constraints).

**Comment by codeliner** [comment]
that chat message is better placed here:

> btw. @gquemener the MinLength deriving was a quick idea of mine, but I took another route. MinLength and other validators are used in JSON-Schema which is used by Event Machine to describe and validate message playloads. JSON-Schema plays well with Swagger UI. Anyway, I thought such derivings would be useful to integrate FPP with Event Machine but as discussed yesterday Event Machine performs input/payload validation first and then hands over message data to whatever message class you want. You can validate that data again using for example conditions in FPP or you trust the application layer that input data is valide and focus on domain logic only. The latter approach ensures that the core domain logic is clean, easy to understand and simple to refactor.

**Comment by codeliner** [comment]
so maybe we should close the issue?

Better support for custom derivings with arguments would still be a nice thing to have, though.

**Comment by prolic** [comment]
Still a little undecided, I let it open for now and handle it once I come back to it.

**Comment by prolic** [comment]
The difference really is this:
```
Foo = String deriving (MinLength(10));
```

VS:
```
Foo = String where
    _:
        | $value < 10 => 'Foo is too short';
```

The latter is a little more to write, but let's you specify the error message

**Comment by gquemener** [comment]
Or

```
exception TooShort = \InvalidArgumentException;
data Foo = String where
    _:
        | $value < 10 => TooShort;
```

:tada:

**Comment by prolic** [comment]
A release 0.1.0 has been tagged. There is currently a rewrite going on, so I will close all open issues. If you still want to resolve this issue yourself, you can submit a pull request to the 0.1.x branch.
