### ISSUE TITLE
Add JsonSchema deriving

### ISSUE THREAD

**Issue by prolic** [prolic/fpp#51]
generates json and writes somewhere

example output: https://app.swaggerhub.com/apis/camuthig/event_machine/1.0.0

/cc @codeliner

**Comment by codeliner** [comment]
Related discussion: https://github.com/prolic/fpp/issues/50#issuecomment-394757450

So maybe this issue can be closed.

**Comment by prolic** [comment]
A release 0.1.0 has been tagged. There is currently a rewrite going on, so I will close all open issues. If you still want to resolve this issue yourself, you can submit a pull request to the 0.1.x branch.
