### ISSUE TITLE
FPP File Watcher config for docker

### ISSUE THREAD

**Issue by codeliner** [prolic/fpp#56]
Program: `docker`
Argument: `run --rm -i -v $ProjectFileDir$:/app -u 1000 -w /app prooph/php:7.1-cli php vendor/prolic/fpp/bin/fpp.php $FileDirRelativeToProjectRoot$/$FileName$`

Note: docker run argument `-u 1000` might be adjusted according to UID of the user who should own the generated files.

**Comment by prolic** [comment]
I use this here (see wiki):
`$ProjectFileDir$/vendor/prolic/fpp/bin/fpp.php $FilePath$`

This however assumes that all fpp files are in one directory (no subdirs).
Benefit is: all fpp files are parsed (not just one), so we have all dependencies loaded.

**Comment by gquemener** [comment]
I use `--user "$(id -u):$(id -g)" to always use current uid and gid (thus creating the files with the good owner)

**Comment by prolic** [comment]
A release 0.1.0 has been tagged. There is currently a rewrite going on, so I will close all open issues. If you still want to resolve this issue yourself, you can submit a pull request to the 0.1.x branch.
