### ISSUE TITLE
Using php keywords breaks fpp

### ISSUE THREAD

**Issue by lunetics** [prolic/fpp#64]
E.g. when you want to use php keywords like "new" or "class" breaks fpp:

e.g.
```
data Bar = Old | New deriving (Enum);
```
results in:
```
Parse Error: Syntax error, unexpected 'New', expecting 'T_STRING' at line 5 on file 'foo.fpp'
```

**Comment by prolic** [comment]
ping @lunetics

**Comment by prolic** [comment]
I close this, if you still feel that there is something I should do about it, please reopen and leave your arguments.
