### ISSUE TITLE
Impossible to use existing marker on data

### ISSUE THREAD

**Issue by gquemener** [prolic/fpp#66]
# Scenario

Given the following "domain.fpp":
```
namespace App;
data Person : \App\User = Person;
```
and the following existing marker:
```php
<?php

declare (strict_types = 1);

namespace App;

interface User
{
}
```
When I run the fpp command
Then the "src/Person.php" file should contain:
```php
<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace App;

final class Person implements \App\User
{
}
```

# Result

This scenario fails with the following error:
```
Exception: Cannot mark data App\Person with unknown marker App\User
```

# Fix
Switch the autoloader flag to true [on this `interface_exists` function call](https://github.com/prolic/fpp/blob/2bfadfb1c67ca875bb3d9757a105c52fc6f82efa/src/builder/buildClassImplements.php#L28).

**Comment by prolic** [comment]
Pr please

**Comment by gquemener** [comment]
When I have time!
