### ISSUE TITLE
Equals on compound VO

### ISSUE THREAD

**Issue by lunetics** [prolic/fpp#72]
Assume following .fpp config

```
data BusinessRelationshipType = B2C | B2B deriving (Enum);
data Channel = Frontend | Idealo | billiger_de deriving (Enum);
data Source = Source {Channel $channel, BusinessRelationshipType $businessRelationshipType } deriving (Equals, FromArray, ToArray);
```
results in following *equals* method:
```
public function equals(Source $source): bool
    {
        if (\get_class($this) !== \get_class($source)) {
            return false;
        }

        return $this->channel->toString() === $source->channel->toString()
            && $this->businessRelationshipType->toString() === $source->businessRelationshipType->toString();
    }
```

unfortunately, toString is not implemented in the enum channel or businessrelationship

**Comment by lunetics** [comment]
Also it's not possible to deriving Equals / ToString / FromString in an Enum.
Fix could be
* either compare $enum->name() === $otherEnum->name()
* make "Equals" deriving possible with Enums and use the Equals method in the compound VO?

What do you think?

**Comment by prolic** [comment]
Are you using latest master? I remember there was a bugfix for this issue some days ago. Enums should use name() method instead of toSring().

**Comment by prolic** [comment]
but maybe this issue is in more then one place in the code base, if so, wanna provide a test-case and fix?

**Comment by lunetics** [comment]
Fixed in latest master
