### ISSUE TITLE
Error in function buildMethodBodyFromAggregateId incorrectly suggests fromArray could solve  problem.

### ISSUE THREAD

**Issue by SimonPrins** [prolic/fpp#93]
The following error message https://github.com/prolic/fpp/blob/master/src/helpers.php#L432 suggests that it can be fixed by having the property in question derive fromArray, however, the function buildMethodBodyFromAggregateId, unlike buildMethodBodyFromPayload does not allow properties that derive fromArray.

I would also suggest making it clear in the error message that the AggregateId is a special case for the first property of an AggregateChanged object and that this is the reason why it is not allowed to use fromArray here.

**Comment by prolic** [comment]
Do you have a usecase for an array as aggregate id? Sounds weird to me.
