### ISSUE TITLE
Blocks on protected keywords protection where it doesn't make sense.

### ISSUE THREAD

**Issue by paales** [prolic/fpp#97]
```fpp
MyNamespace {
    data Condition =  New | AsNew | Good | Reasonable | Moderate deriving(Enum);
}
```

This gives an error because the `New` keyword is in there, but in my opinion this should be allowed.

Also (as in singular of 'returns'):

```fpp
MyNamespace\Return {

}
```

```
Parse Error: Syntax error, unexpected 'Return', expecting 'T_STRING' at line 1 on file 'domain.fpp'
```

**Comment by prolic** [comment]
wanna provide a PR? hint: problem is the parser logic, it expects a T_STRING but receives a keyword instead, so you just have to allow this as well. should be simple to fix.

**Comment by paales** [comment]
This is impossible to fix, the parser chokes on it, but if I fix it the generated classes are invalid as well :)
